<?php

namespace DataLayerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    /**
     * Returns most Recents Comments
     * @param $numDays number of days to check in the past
     */
    public function getArticleEmailsFromRecentComments($numDays)
    {
        $queryBuilder = $this->_em->createQueryBuilder();

        $queryBuilder
            ->select('c')
            ->from($this->_entityName , 'c')
            ->where("c.creationDate > :date")
            ->setParameter('date' , date('Y-m-d H:i:s', time() - 86400 * $numDays));

        $results = $queryBuilder->getQuery()->getResult();

        $emails = [];
        foreach($results as $result)
        {
            $emails[] = $result->getArticle()->getEmail();
        }

        //remove doublon
        $emails = array_unique($emails);

        return $emails;
    }
}